# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='service guid')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='service name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(editable=False, max_length=20, verbose_name='service type')),
            ],
        ),
        migrations.CreateModel(
            name='TmsService',
            fields=[
                ('geoservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qms_core.GeoService')),
                ('url', models.URLField()),
                ('z_min', models.IntegerField(blank=True, null=True)),
                ('z_max', models.IntegerField(blank=True, null=True)),
                ('y_origin_top', models.BooleanField(default=False)),
            ],
            bases=('qms_core.geoservice',),
        ),
        migrations.CreateModel(
            name='WfsService',
            fields=[
                ('geoservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qms_core.GeoService')),
                ('url', models.URLField()),
            ],
            bases=('qms_core.geoservice',),
        ),
        migrations.CreateModel(
            name='WmsService',
            fields=[
                ('geoservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qms_core.GeoService')),
                ('url', models.URLField()),
                ('params', models.CharField(blank=True, max_length=1024, null=True)),
                ('layers', models.CharField(blank=True, max_length=1024, null=True)),
                ('turn_over', models.BooleanField(default=False)),
            ],
            bases=('qms_core.geoservice',),
        ),
    ]
