# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0002_geoservice_tmsservice_wfsservice_wmsservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='epsg',
            field=models.IntegerField(blank=True, null=True, verbose_name='EPSG Code'),
        ),
    ]
