# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0003_geoservice_epsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='icon guid')),
                ('icon', models.ImageField(max_length=200, upload_to='service_icon/', verbose_name='icon')),
                ('name', models.CharField(max_length=200, verbose_name='icon name')),
                ('is_private', models.BooleanField(default=False, verbose_name='icon is private')),
            ],
        ),
    ]
