# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0004_serviceicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_core.ServiceIcon'),
        ),
    ]
