# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0006_auto_20160412_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsservice',
            name='format',
            field=models.CharField(blank=True, choices=[('image/png', 'PNG'), ('image/png8', 'PNG8'), ('image/png24', 'PNG24'), ('image/png32', 'PNG32'), ('image/gif', 'GIF'), ('image/bmp', 'BMP'), ('image/jpeg', 'JPEG'), ('image/tiff', 'TIFF'), ('image/tiff8', 'TIFF8'), ('image/geotiff', 'GeoTIFF'), ('image/geotiff8', 'GeoTIFF8'), ('image/svg+xml', 'SVG')], max_length=128, null=True),
        ),
    ]
