# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0007_wmsservice_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsservice',
            name='layer',
            field=models.CharField(default='SET_THIS!', max_length=1024, verbose_name='Layer name (namespace:featuretype)'),
            preserve_default=False,
        ),
    ]
