# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0009_geojsonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='copyright_link',
            field=models.URLField(blank=True, null=True, verbose_name='copyright url'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='copyright text'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='license_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='license name'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='license_url',
            field=models.URLField(blank=True, null=True, verbose_name='license url'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='terms_of_use_url',
            field=models.URLField(blank=True, null=True, verbose_name='terms of use url'),
        ),
    ]
