# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0011_auto_20160422_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoservice',
            old_name='copyright_link',
            new_name='copyright_url',
        ),
    ]
