# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0012_auto_20160422_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextgisuser',
            name='nextgis_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='nextgis guid'),
        ),
    ]
