# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 18:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0014_nextgisuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 14, 18, 8, 4, 486371, tzinfo=utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoservice',
            name='source',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='source url'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='nextgis_guid'),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 14, 18, 8, 18, 682409, tzinfo=utc), verbose_name='updated at'),
            preserve_default=False,
        ),
    ]
