# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0015_auto_20161114_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoservice',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='source'),
        ),
    ]
