# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0016_auto_20161125_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonservice',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='geoservice',
            name='copyright_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='copyright url'),
        ),
        migrations.AlterField(
            model_name='geoservice',
            name='license_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='license url'),
        ),
        migrations.AlterField(
            model_name='geoservice',
            name='source_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='source url'),
        ),
        migrations.AlterField(
            model_name='geoservice',
            name='terms_of_use_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='terms of use url'),
        ),
        migrations.AlterField(
            model_name='tmsservice',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='wfsservice',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='wmsservice',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
