# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0017_auto_20170110_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_at', models.DateTimeField(auto_now_add=True, verbose_name='check state date/time')),
                ('check_duration', models.FloatField(null=True)),
                ('cumulative_status', models.CharField(choices=[('failed', 'failed'), ('works', 'works'), ('problematic', 'problematic')], max_length=50)),
                ('http_code', models.IntegerField(null=True)),
                ('http_response', models.CharField(max_length=2048, null=True)),
                ('error_type', models.CharField(choices=[('timeout', 'timeout'), ('missing layer', 'missing layer'), ('invalid response', 'invalid response'), ('wrong url', 'wrong url'), ('not found response', 'not found response'), ('unsupported service', 'unsupported service')], max_length=50, null=True)),
                ('error_text', models.CharField(max_length=2048, null=True)),
                ('geoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms_core.GeoService')),
            ],
        ),
        migrations.AddField(
            model_name='geoservice',
            name='last_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for', to='qms_core.GeoServiceStatus'),
        ),
    ]
