# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-28 13:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0021_auto_20170626_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservice',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geoservice',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
