# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_core', '0022_auto_20170628_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoservice',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
    ]
