# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qms_core', '0017_auto_20170110_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('report_type', models.CharField(choices=[('license_violation', 'License violation'), ('service_not_working', 'Service not working'), ('other_problem', 'Other problem')], max_length=20)),
                ('report_message', models.TextField(blank=True, null=True)),
                ('report_dt', models.DateTimeField(auto_now_add=True)),
                ('geo_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms_core.GeoService')),
                ('reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='nextgis_guid')),
            ],
        ),
    ]
