# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='report_type',
            field=models.CharField(choices=[('license_violation', 'License violation'), ('service_not_working', 'Service not working'), ('general_feedback', 'General feedback'), ('other_problem', 'Other problem')], max_length=20),
        ),
    ]
