version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: registry.nextgis.com/qms_dj22py38:1.0.4
    environment:
      - DATABASE_NAME=qms_server3
      - DATABASE_USER=qms_server
      - DATABASE_PASS=tf7yi8kd
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - EMAIL_HOST=prod.vpn.nextgis.net
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=service@nextgis.com
      - EMAIL_HOST_PASSWORD=sbOqj96DwIX7avIe
      - DEFAULT_FROM_EMAIL=qms@nextgis.com
      - EMAIL_SUBJECT_PREFIX=[NextGIS QMS Dev feedback]
      - NGID_CLIENT_ID=jQBKtVVaEWTIZT9yZQt9pet6168iTD5sR27dYXT8
      - NGID_CLIENT_SECRET=AlWUFBZXWT0a7wzuFt1rvajgVDuyQXwIOvEWPRVjAJm1Wcx9b0vPTYCPgPfaaqpEGGmZNK9MKNQpfl9n1V2VUwaAG8XrFAybxpCDz1r8m5wvfnQZZdxBZ3aHhmZkVw77
      - ALLOWED_HOST=*
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - IS_DEBUG=false
    command: "./start_socket.sh"
    # command: "./start_http.sh"
    network_mode: host
    volumes: 
      - socket:/opt/socket
      - django-media:/opt/app/qms_server/media
      - django-static:/opt/app/qms_server/static
      - tmp-nginx:/tmp/nginx
      - nginx-conf:/opt/app/nginx

  nginx:
    depends_on: 
      - web
    image: nginx
    user: nginx
    volumes:
      - socket:/opt/socket
      - django-media:/django-media
      - django-static:/django-static
      - tmp-nginx:/tmp
      - nginx-conf:/etc/nginx-conf
      # - /home/sk/py3/quickmapservices_server/docker/custom_files/nginx:/etc/nginx-conf
    ports:
    - "80:8000"
    command: [nginx, '-c', '/etc/nginx-conf/nginx_qms.conf', '-g', 'daemon off;']
volumes:
  socket:
  django-media:
  django-static:
  nginx-conf:
  tmp-nginx:
