version: '3.7'

services:
    web:
      build:
        context: ../
        dockerfile: ./docker/Dockerfile
      image: registry.nextgis.com/qms:dj22py38
      ports:
        - 8000:8080
      environment:
        - DATABASE_NAME=qms_server3
        - DATABASE_USER=qms_server
        - DATABASE_PASS=tf7yi8kd
        - DATABASE_HOST=localhost
        - DATABASE_PORT=5432
        - ALLOWED_HOST=*
        - OAUTHLIB_INSECURE_TRANSPORT=1
        - IS_DEBUG=false
      command: "./start.sh"
      network_mode: host
      # volumes:
        # - ../qms_server:/opt/app/qms_server
        # - ./custom_files/settings_local.py:/opt/app/qms_server/qms_server/settings_local.py
volumes:
  db_dir: {}
