version: '3.7'

services:
    web:
      build:
        context: ../
        dockerfile: ./docker/Dockerfile
      image: registry.nextgis.com/qms_dj22py38:1.0.2
      ports:
        - 8000:8080
      environment:
        - DATABASE_NAME=qms_server3
        - DATABASE_USER=qms_server
        - DATABASE_PASS=tf7yi8kd
        - DATABASE_HOST=localhost
        - DATABASE_PORT=5432
        - EMAIL_HOST=prod.vpn.nextgis.net
        - DEFAULT_FROM_EMAIL=qms@nextgis.com
        - EMAIL_SUBJECT_PREFIX=[NextGIS QMS Dev feedback]
        - NGID_CLIENT_ID=jQBKtVVaEWTIZT9yZQt9pet6168iTD5sR27dYXT8
        - NGID_CLIENT_SECRET=AlWUFBZXWT0a7wzuFt1rvajgVDuyQXwIOvEWPRVjAJm1Wcx9b0vPTYCPgPfaaqpEGGmZNK9MKNQpfl9n1V2VUwaAG8XrFAybxpCDz1r8m5wvfnQZZdxBZ3aHhmZkVw77
        - ALLOWED_HOST=*
        - OAUTHLIB_INSECURE_TRANSPORT=1
        - IS_DEBUG=false
      command: "./start.sh"
      network_mode: host
      # BE CAREFUL: volumes may damage unzipping of /media contents (see start.sh)
      # volumes:
        # - ../qms_server:/opt/app/qms_server
        # - ./custom_files/settings_local.py:/opt/app/qms_server/qms_server/settings_local.py
volumes:
  db_dir: {}
